@startmindmap
<style>
mindmapDiagram {
  .green {
    BackgroundColor lightgreen
  }
  .rose {
    BackgroundColor #FFBBCC
  }
  .blue {
    BackgroundColor lightblue
  }
}
</style>
* Projekte
** n/a
***_ Bauer Alina 5
***_ Kraml Friedrich 5
***_ Mahringer Daniel 5
***_ Brandstetter Elias 5
***_ Ursprung Christoph 4-
***_ Binder Sophie 1


** Zeiterfassung <<green>>
***_ Adelwöhrer Leonie 1
** Organisationssoftware <<rose>>
***_ Fröller Jonas
** Action-Server <<blue>>
***_ Hofer Jakob 1
** Website mit Fragen <<blue>>
***_ Michel Jakob
** Sozial-Dings <<rose>>
***_ Schlager Jakob 4-
** pdf-Server <<rose>>
***_ Pölderl Laurin
** DateOn <<rose>>
***_ Mayrhuber Lukas 4-
** App zum Schnapsen <<green>>
***_ Wagner Moritz 1
*** Kartenspiel-Lernapp <<green>>
****_ Slabschi Maximilian
** Website HTL Clubs
***_ Puchner Manuel 1
** Hotel-Tinder <<green>>
***_ Aschenberger Maria
** Mülltrennung <<rose>>
***_ Wolfslehner Mattias 3
** Stromverbrauchs-Visualisierung <<green>>
***_ Ruep Michael
***_ Puchner Manuel
** Discord-Voice-Assistent
***_ Schablinger Mathias
** Adopted Cats <<green>>
***_ Stöger Sophie
** Night-Bar-Inventur und online-Besteller <<rose>>
***_ Wakolbinger Nico
** Fahrgemeinschaft <<green>>
***_ Schnalzenberger Isabel
** Google Maps Clone <<rose>>
***_ Stieg Josef
** Auftritt-Reminder <<rose>>
***_ Stenz_ Michael
** Browser-ToDo-List <<rose>>
***_ Vlajic Stevan


@endmindmap
