@startmindmap

* Projekte
** n/a
*** Bauer Alina 5
*** Kraml Friedrich 5
*** Mahringer Daniel 5
*** Brandstetter Elias 5
*** Ursprung Christoph 4-
*** Pölderl Laurin


** Zeiterfassung
*** Adelwöhrer Leonie 1
** Organisationssoftware
*** Fröller Jonas
** Action-Server
*** Hofer Jakob 1
** Website mit Fragen
*** Michel Jakob
** Sozial-Dings
*** Schlager Jakob 4-
** DateOn
*** Mayrhuber Lukas 4-
** App zum Schnapsen
*** Wagner Moritz 1
** Website HTL Clubs
*** Puchner Manuel 1
** Hotel-Tinder
*** Aschenberger Maria
** Science-Fiction
*** Wolfslehner Mattias 3





@endmindmap
