@startmindmap
* Karten spielen
**_ Slabschi Maximilian
**_ Wagner Moritz (PL)
**_ Schablinger Mathias
**_ Michel Jakob
* Fahrgemeinschaft
**_ Schnalzenberger Isabel (PL)
**_ Kraml Friedrich
**_ Mahringer Daniel
**_ Pölderl Laurin
* Hotel Matcher
**_ Brandstätter Elias
**_ Schlager Jakob
**_ Aschenberger Maria (PL)
**_ Fröller Jonas
**_ Stieg Josef
* Adopted Cats
**_ Stöger Sophie (PL)
**_ Binder Sophie
**_ Ursprung Christoph
**_ Wolfslehner, Mattias
**_ Kovacevic Magdalena
* Stromverbrauchs-Visualisierung
**_ Ruep Michael (PL)
**_ Puchner Manuel
**_ Mayrhuber Lukas
**_ Wakolbinger Nico
**_ Vlajic Stevan
* Zeiterfassung
**_ Adelwöhrer Leonie (PL)
**_ Stenz Michael
**_ Hofer Jakob
**_ Bauer Alina
@endmindmap